_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: /work/gg0877/g260217/al_paper/eurosat_s2_al/moco/.submitit/%j
cpus_per_task: 16
job_name: mocosettings
nodes: 1
ntasks_per_node: 1
partition: gpu
gpus_per_node: 1
timeout_min: 600
additional_parameters:
    account: gg0877
    constraint: a100_80
    time: 25
    output: /work/gg0877/g260217/al_paper/eurosat_s2_al/moco/slurm-%j.out
    signal: SIGUSR1@90
    wckey: null
    mem: 0
    mail_user: david.pogorzelski@hereon.de
    mail-type: FAIL
