defaults:
    - override hydra/launcher: levante.yaml
    - _self_
    
seed: 1
n_init_labeled: 32
n_query: 32
n_round: 10
dataset_name: "EuroSAT"
strategy_name: "RandomSampling"
init_strategy: "random"
balance: True